### ISSUE TITLE
typo in setup.py

### ISSUE THREAD

**Issue by blaylockbk** [joxtoby/beltzer#1]
First, thanks for publishing this! I just saw a friend like your LinkedIn post and I'm glad I noticed it. As this package matures, I'd like to add it as an optional dependency for my [Herbie](https://github.com/blaylockbk/Herbie) package, which currently assumes the .idx file exists on the remote. 

Anyways, I wanted to let you know of a minor typo...

In the `setup.py` file, `README.rst` should be `README.md`

**Comment by joxtoby** [comment]
Thanks Brian good catch - got it fixed.
